### ISSUE TITLE
Nearby tracking - Frontend

### ISSUE THREAD

**Issue by anibalsolon** [tx-covid19/beiwe-backend-serverless#27]
- [ ] Use Nearby API to identify contacts
- [ ] Store received and transmitted UIDs in safe storage
- [ ] Handle push notification to check if there was a contact and show instructions if contact discovered
