### ISSUE TITLE
Test tracker input - Frontend

### ISSUE THREAD

**Issue by puorc** [tx-covid19/beiwe-backend-serverless#30]
- [ ] User enters test ID either with QR code scanner or text entry
- [ ] send user EID, test ID, timestamp, and location to backend
- [ ] in-app page to show users' tests
